# Project Information
site_name: 'Zebreco'
site_description: 'Zebreco Documentation'
site_author: 'outer/edge'
site_favicon: 'images/favicon.ico'
copyright: 'Copyright &copy; 2017 Zebreco'
theme: 'material'

# Extensions
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)

# Options
extra:
    palette:
        primary: 'Red'
        accent: 'Blue'

    logo: 'images/zebreco_logo.png'
    
    social:
        - type: 'github'
          link: 'https://github.com/zebreco'
        - type: 'twitter'
          link: 'https://twitter.com/zebreco'

    feature:
        tabs: true

# Google Analytics
google_analytics:
    - 'UA-1765263-13'
    - 'auto'

# Repository 
repo_url: https://github.com/zebreco/documentation
repo_name: 'GitHub'

# Layout
pages:
    - Docs:
        - Welcome: 'index.md'
        - Getting Started: 'getting-started.md'
        - Dashboard: 'dashboard.md'
        - Settings:
            - 'Settings Overview': 'settings.md'
            - 'My Profile': 'settings/my-profile.md'
            - 'Account Settings': 'settings/account-settings.md'
            - 'User & Department Settings': 'settings/users-departments.md'
            - 'Ticket Settings': 'settings/ticket-settings.md'
            - 'Task Settings': 'settings/task-settings.md'
            - 'Project Settings': 'settings/project-settings.md'
            - 'Lead Settings': 'settings/lead-settings.md'
            - 'Sales Settings': 'settings/sales-settings.md'
            - 'Document Settings': 'settings/document-settings.md'
            - 'Time Settings': 'settings/time-settings.md'
        - Tickets: 'tickets.md'
        - Tasks: 'tasks.md'
        - Contacts: 'contacts.md'
        - Projects: 'projects.md'
        - Sales: 'sales.md'
        - Time: 'time.md'
        - Calendar: 'calendar.md'
        - Reports: 'reports.md'
        - Labels: 'labels.md'
    - API:
        - Getting Started: 'api/api-gettingstarted.md'
        - Authentication: 'api/api-authentication.md'
        - Reading from the API: 'api/api-reading.md'
        - Writing to the API: 'api/api-writing.md'
        - Handling API responses: 'api/api-responses.md'
        - Models:
            - 'Calendar Event': 'api/api-calendarevent.md'
            - 'Contact': 'api/api-contact.md'
            - 'Contact Role': 'api/api-contactrole.md'
            - 'Custom Field': 'api/api-customfield.md'
            - 'Department': 'api/api-department.md'
            - 'Document': 'api/api-document.md'
            - 'File': 'api/api-file.md'
            - 'Filter': 'api/api-filter.md'
            - 'Invoice': 'api/api-invoice.md'
            - 'Label': 'api/api-label.md'
            - 'Lead': 'api/api-lead.md'
            - 'Lead Lost Reason': 'api/api-leadlostreason.md'
            - 'Lead Source': 'api/api-leadsource.md'
            - 'Log': 'api/api-log.md'
            - 'Mail Template': 'api/api-mailtemplate.md'
            - 'Note': 'api/api-note.md'
            - 'Package': 'api/api-package.md'
            - 'Product': 'api/api-product.md'
            - 'Project': 'api/api-project.md'
            - 'Project Role': 'api/api-projectrole.md'
            - 'Project Status': 'api/api-projectstatus.md'
            - 'Project Template': 'api/api-projecttemplate.md'
            - 'Quote': 'api/api-quote.md'
            - 'Task': 'api/api-task.md'
            - 'Ticket': 'api/api-ticket.md'
            - 'Ticket Post': 'api/api-ticketpost.md'
            - 'Time': 'api/api-time.md'
            - 'Time Status': 'api/api-timestatus.md'
            - 'Track': 'api/api-track.md'
            - 'Track Task': 'api/api-tracktask.md'
            - 'Webhook': 'api/api-webhook.md'
            
        
