#!/bin/bash
echo "=> Pushing to built branch"

#git fetch --unshallow origin

CONTAINER_ID=$(docker create $IMAGE_NAME)

git config user.name "Docker Cloud"
git config user.email "test@example.com"
git checkout built

docker cp $CONTAINER_ID:/var/www/site/. .

git add .
git commit -m "[built] $COMMIT_MSG ($SOURCE_COMMIT)"
git push origin built
